name: Deploy

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Parse major, minor and path from version tag
        run: |
          VERSION=${GITHUB_REF:11}
          MAJOR=`echo "$VERSION" | cut -d . -f 1`
          MINOR=`echo "$VERSION" | cut -d . -f 2`
          PATCH=`echo "$VERSION" | cut -d . -f 3`
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "major=$MAJOR" >> $GITHUB_ENV
          echo "minor=$MINOR" >> $GITHUB_ENV
          echo "patch=$PATCH" >> $GITHUB_ENV

      - name: Registry Login (ghcr.io)
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and publish image
        run: |
          IMG=ghcr.io/${{ github.repository }}
          docker build \
            --tag $IMG:latest \
            --tag $IMG:${{ env.major }}.latest \
            --tag $IMG:${{ env.major }}.${{ env.minor }}.latest \
            --tag $IMG:${{ env.major }}.${{ env.minor }}.${{ env.patch }}.latest \
            .
          docker push --all-tags ${IMG}
